In [3]:
import numpy as np
import math


# (a) Berechnen Sie den Winkel $\alpha$ in Grad zwischen den folgenden beiden Vektoren $a=[1.,1.77]$ und $b=[1.5,1.5]$
a = np.array([-1.,1.77])
b = np.array([1.5,1.5])
# YOUR CODE HERE
#print(np.dot(a,b))
c = np.dot(a,b)/ (np.linalg.norm(a)*np.linalg.norm(b)) # -> cosine of the angle
#print(c)
#angle = np.arccos(c) # out of range?!
angle = np.arccos(np.clip(c, -1, 1)) # if you really want the angle
print('Angle in deg: {0:.2f}°'.format(np.degrees(angle)))

# (b) Gegeben ist die quadratische regulaere Matrix A und ein Ergbnisvektor b. Rechnen Sie unter Nutzung der Inversen die Loesung x des Gleichungssystems Ax = b aus.
# YOUR CODE HERE
M1 = np.matrix('2 3 4; 3 -2 -1; 5 4 3')
M2 = np.matrix('1.4; 1.2; 1.4')
x = np.linalg.inv(M1)*M2
print('Aufgabe b: Vector x:\n',x)

# (c) Schreiben Sie eine Funktion die das Matrixprodukt berechnet. Nutzen Sie dafür nicht die Numpy Implementierung.
# Hinweis: Fangen Sie bitte mögliche falsche Eingabegroessen in der Funktion ab und werfen einen AssertionError
# assert Expression[, Arguments]

def matmult(M1, M2):
    # YOUR CODE HERE
    assert (M1.shape[1]==M2.shape[0]), "Matrix dimensions don't fit"
    assert (len(M1.shape)==2 and len(M2.shape)==2), "Matrix must have 2dim"
    # create result matrix
    Mres = np.zeros((M1.shape[0],M2.shape[1]))
    
    for r in range(M1.shape[0]):
        for c in range(M2.shape[1]):
            Mres[r,c] = M1[r,:]*M2[:,c]
            
    return Mres
    

M3 = np.matrix('1 2 3; 3 -2 -1; 5 4 3')
M4 = np.matrix('1 2; 3 -2; 5 8')
M5 = matmult(M3, M4)
print('Self made matrix mult:\n',M5)

M1 = np.matrix('1 2; 3 4; 5 6')
M2 = np.matrix('2 0; 0 2')
print(M1, M2)
M_res = matmult(M3, M4)
print(M_res)

Angle in deg: 74.47°
Aufgabe b: Vector x:
 [[ 0.3]
 [-0.4]
 [ 0.5]]
Self made matrix mult:
 [[22. 22.]
 [-8.  2.]
 [32. 26.]]
[[1 2]
 [3 4]
 [5 6]] [[2 0]
 [0 2]]
[[22. 22.]
 [-8.  2.]
 [32. 26.]]
