In [5]:
from __future__ import print_function
import torch

# show plot first run
%matplotlib inline 
# test autocompletion with tab or tab+shift
%config IPCompleter.greedy=True 

x = torch.empty(5, 3)
print(x)
x = torch.rand(5,3)
print(x)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[2.9498e+15, 3.0637e-41, 3.2922e+15],
        [3.0637e-41, 8.9683e-44, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 1.9576e+14],
        [3.0637e-41, 1.4357e-01, 1.2804e-01],
        [7.8666e-01, 7.7441e-01, 4.9011e-01]])
tensor([[0.6698, 0.5240, 0.3413],
        [0.8809, 0.4208, 0.8197],
        [0.7555, 0.5545, 0.2779],
        [0.6509, 0.9676, 0.0804],
        [0.7271, 0.2940, 0.5024]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.5506, -1.8712,  0.5918],
        [-0.5477, -1.0508,  0.1095],
        [ 0.7736, -0.6184,  0.1304],
        [ 1.2242, -1.3378, -0.8045],
        [-0.1276, -0.1757,  2.8646]])


In [11]:
print(x.size())


torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
# option 1 to add
print(x + y)

tensor([[ 1.7658, -1.3942,  0.9217],
        [ 0.0139, -0.4153,  0.4695],
        [ 0.9291, -0.0581,  0.4536],
        [ 1.8095, -0.6405,  0.1215],
        [ 0.3428, -0.0594,  3.0082]])


In [13]:
# option 2 to add
print(torch.add(x, y))

tensor([[ 1.7658, -1.3942,  0.9217],
        [ 0.0139, -0.4153,  0.4695],
        [ 0.9291, -0.0581,  0.4536],
        [ 1.8095, -0.6405,  0.1215],
        [ 0.3428, -0.0594,  3.0082]])


In [14]:
# option 3 to add
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

result = torch.add(x, y)
print(result)

tensor([[ 1.7658, -1.3942,  0.9217],
        [ 0.0139, -0.4153,  0.4695],
        [ 0.9291, -0.0581,  0.4536],
        [ 1.8095, -0.6405,  0.1215],
        [ 0.3428, -0.0594,  3.0082]])
tensor([[ 1.7658, -1.3942,  0.9217],
        [ 0.0139, -0.4153,  0.4695],
        [ 0.9291, -0.0581,  0.4536],
        [ 1.8095, -0.6405,  0.1215],
        [ 0.3428, -0.0594,  3.0082]])


In [15]:
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.7658, -1.3942,  0.9217],
        [ 0.0139, -0.4153,  0.4695],
        [ 0.9291, -0.0581,  0.4536],
        [ 1.8095, -0.6405,  0.1215],
        [ 0.3428, -0.0594,  3.0082]])


In [16]:
print(x[:, 1])

tensor([-1.8712, -1.0508, -0.6184, -1.3378, -0.1757])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
print(x)
print(y)
print(z)

tensor([[ 0.3038,  0.4813, -0.7551, -1.0306],
        [ 0.5445,  2.0052, -1.1334,  1.0243],
        [ 0.0364, -0.7656, -0.1027,  0.3696],
        [ 0.5671,  0.2990, -1.1274,  0.3427]])
tensor([ 0.3038,  0.4813, -0.7551, -1.0306,  0.5445,  2.0052, -1.1334,  1.0243,
         0.0364, -0.7656, -0.1027,  0.3696,  0.5671,  0.2990, -1.1274,  0.3427])
tensor([[ 0.3038,  0.4813, -0.7551, -1.0306,  0.5445,  2.0052, -1.1334,  1.0243],
        [ 0.0364, -0.7656, -0.1027,  0.3696,  0.5671,  0.2990, -1.1274,  0.3427]])


In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.8102])
-1.8101755380630493


In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [25]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [26]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [27]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [28]:
print(y.grad_fn)

In [29]:
z = y + 2
print(z)

tensor([[5., 5.],
        [5., 5.]], grad_fn=<AddBackward0>)


In [30]:
print(z.grad_fn)

In [31]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [32]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

False
True
tensor(40.5273, grad_fn=<SumBackward0>)


In [33]:
#Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent 
#to out.backward(torch.tensor(1.)).
out.backward() #Gradients



In [34]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
