In [10]:
from __future__ import print_function
import torch

# show plot first run
%matplotlib inline 
# test autocompletion with tab or tab+shift
%config IPCompleter.greedy=True 

x = torch.empty(5, 3)
print(x)
x = torch.rand(5,3)
print(x)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[-6.0123e-10,  3.0862e-41, -5.2837e-10],
        [ 3.0862e-41,  6.4564e-33,  1.6673e-24],
        [ 2.6685e-23,  1.7331e-24,  3.9132e-34],
        [ 6.6490e-33,  6.8309e-21,  1.5286e-36],
        [ 6.5038e-33,  9.1838e-41,  9.1837e-41]])
tensor([[0.6316, 0.2185, 0.0543],
        [0.2805, 0.8604, 0.8324],
        [0.6745, 0.1560, 0.5398],
        [0.3711, 0.5163, 0.8110],
        [0.0104, 0.9116, 0.1805]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [13]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.0774,  1.3426,  0.7673],
        [-0.3943,  0.6399,  0.4318],
        [ 0.5081, -1.9040,  2.0715],
        [ 1.1444, -0.2831,  0.2901],
        [ 1.6749, -0.7960,  0.6929]])


In [14]:
print(x.size())


torch.Size([5, 3])


In [15]:
y = torch.rand(5, 3)
# option 1 to add
print(x + y)

tensor([[ 0.5522,  1.8889,  1.3795],
        [-0.1930,  1.0557,  0.8510],
        [ 1.4898, -1.5135,  2.9343],
        [ 1.5639, -0.1329,  0.5640],
        [ 2.5337, -0.4869,  1.4400]])


In [17]:
# option 2 to add
print(torch.add(x, y))

tensor([[ 0.5522,  1.8889,  1.3795],
        [-0.1930,  1.0557,  0.8510],
        [ 1.4898, -1.5135,  2.9343],
        [ 1.5639, -0.1329,  0.5640],
        [ 2.5337, -0.4869,  1.4400]])


In [19]:
# option 3 to add
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

result = torch.add(x, y)
print(result)

tensor([[ 0.5522,  1.8889,  1.3795],
        [-0.1930,  1.0557,  0.8510],
        [ 1.4898, -1.5135,  2.9343],
        [ 1.5639, -0.1329,  0.5640],
        [ 2.5337, -0.4869,  1.4400]])
tensor([[ 0.5522,  1.8889,  1.3795],
        [-0.1930,  1.0557,  0.8510],
        [ 1.4898, -1.5135,  2.9343],
        [ 1.5639, -0.1329,  0.5640],
        [ 2.5337, -0.4869,  1.4400]])


In [20]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5522,  1.8889,  1.3795],
        [-0.1930,  1.0557,  0.8510],
        [ 1.4898, -1.5135,  2.9343],
        [ 1.5639, -0.1329,  0.5640],
        [ 2.5337, -0.4869,  1.4400]])
