In [1]:
from __future__ import print_function
import torch

# show plot first run
%matplotlib inline 
# test autocompletion with tab or tab+shift
%config IPCompleter.greedy=True 

x = torch.empty(5, 3)
print(x)
x = torch.rand(5,3)
print(x)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6746, 0.6786, 0.2161],
        [0.1697, 0.0359, 0.9262],
        [0.1874, 0.9009, 0.6215],
        [0.8872, 0.5338, 0.9863],
        [0.4426, 0.7875, 0.2154]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [2]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [3]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [4]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.5880, -1.1461, -1.4387],
        [-0.3851, -0.1600, -0.7977],
        [ 0.3409,  0.6212, -1.5632],
        [-0.7731,  0.1566,  0.2709],
        [ 1.5880,  2.1779, -0.4541]])


In [5]:
print(x.size())


torch.Size([5, 3])


In [6]:
y = torch.rand(5, 3)
# option 1 to add
print(x + y)

tensor([[ 0.8876, -1.0110, -0.8457],
        [-0.2954,  0.0145, -0.0348],
        [ 0.5991,  1.1438, -1.5064],
        [ 0.2029,  0.8364,  0.6617],
        [ 2.4635,  3.0095, -0.0601]])


In [7]:
# option 2 to add
print(torch.add(x, y))

tensor([[ 0.8876, -1.0110, -0.8457],
        [-0.2954,  0.0145, -0.0348],
        [ 0.5991,  1.1438, -1.5064],
        [ 0.2029,  0.8364,  0.6617],
        [ 2.4635,  3.0095, -0.0601]])


In [8]:
# option 3 to add
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

result = torch.add(x, y)
print(result)

tensor([[ 0.8876, -1.0110, -0.8457],
        [-0.2954,  0.0145, -0.0348],
        [ 0.5991,  1.1438, -1.5064],
        [ 0.2029,  0.8364,  0.6617],
        [ 2.4635,  3.0095, -0.0601]])
tensor([[ 0.8876, -1.0110, -0.8457],
        [-0.2954,  0.0145, -0.0348],
        [ 0.5991,  1.1438, -1.5064],
        [ 0.2029,  0.8364,  0.6617],
        [ 2.4635,  3.0095, -0.0601]])


In [9]:
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.8876, -1.0110, -0.8457],
        [-0.2954,  0.0145, -0.0348],
        [ 0.5991,  1.1438, -1.5064],
        [ 0.2029,  0.8364,  0.6617],
        [ 2.4635,  3.0095, -0.0601]])


In [10]:
print(x[:, 1])

tensor([-1.1461, -0.1600,  0.6212,  0.1566,  2.1779])


In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
print(x)
print(y)
print(z)

tensor([[-0.7036, -0.5114, -0.8026, -1.2694],
        [ 0.3082,  0.7339, -0.8834, -0.2178],
        [ 1.9247,  1.7329, -0.2819, -0.3473],
        [ 0.1965, -0.1655, -1.2909, -0.4221]])
tensor([-0.7036, -0.5114, -0.8026, -1.2694,  0.3082,  0.7339, -0.8834, -0.2178,
         1.9247,  1.7329, -0.2819, -0.3473,  0.1965, -0.1655, -1.2909, -0.4221])
tensor([[-0.7036, -0.5114, -0.8026, -1.2694,  0.3082,  0.7339, -0.8834, -0.2178],
        [ 1.9247,  1.7329, -0.2819, -0.3473,  0.1965, -0.1655, -1.2909, -0.4221]])


In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8487])
0.8486653566360474


In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [18]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [19]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [21]:
print(y.grad_fn)

In [22]:
z = y + 2
print(z)

tensor([[5., 5.],
        [5., 5.]], grad_fn=<AddBackward0>)


In [23]:
print(z.grad_fn)

In [24]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [25]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

False
True
tensor(849.0409, grad_fn=<SumBackward0>)


In [30]:
#Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent 
#to out.backward(torch.tensor(1.)).
out.backward() #Gradients



RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [31]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
