In [1]:
import torch
# show plot first run
%matplotlib inline 
# test autocompletion with tab or tab+shift
%config IPCompleter.greedy=True 

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [17]:
z = 3*((x + 2)**2)
# or
# y = x + 2
# z = y * y * 3

print(z)

tensor([11.1439,  5.3240,  9.2217], grad_fn=<MulBackward0>)


In [18]:
print(z.grad_fn)

In [19]:
out = z.mean()
print(z)
print(out)

tensor([11.1439,  5.3240,  9.2217], grad_fn=<MulBackward0>)
tensor(8.5632, grad_fn=<MeanBackward0>)


In [20]:
out.backward()
print(x.grad)

tensor([ 208.6547, 2050.6643,    3.7113])


In [21]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-100.1335,  639.5954,  997.8317], grad_fn=<MulBackward0>)


In [22]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [23]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [24]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())
x.eq(y).all()

True
False
tensor(True)
