In [1]:
import numpy as np

# show plot first run
#%matplotlib inline 
# test autocompletion with tab or tab+shift
%config IPCompleter.greedy=True 

In [2]:
# o: coordinates of 'o' in world coord system
o = np.array([2.0, 2.0, 0.0])
# coordinates of u,v in local coordinates
u = np.array([4.0,3.0,0.0]) # x
v = np.array([1.0,4.0,0.0]) # y

In [3]:
e1 = (u - o) / np.linalg.norm(u-o) # x
e2 = (v - o) / np.linalg.norm(v-o) # y
e3 = np.cross(e1,e2) # z
#e1 = (u ) / np.linalg.norm(u) # x
#e2 = (v) / np.linalg.norm(v) # y
#e3 = np.cross(e1,e2) # z

In [4]:
print(e1,e2,e3)

[0.89442719 0.4472136  0.        ] [-0.4472136   0.89442719  0.        ] [ 0. -0.  1.]


In [5]:
M = np.zeros((3,3))
M[0,:3] = e1
M[1,:3] = e2
M[2,:3] = e3
M

array([[ 0.89442719,  0.4472136 ,  0.        ],
       [-0.4472136 ,  0.89442719,  0.        ],
       [ 0.        , -0.        ,  1.        ]])

In [6]:
# from world to local coord system
v = np.array([1.0,4.0,0.0]) # y
v = v-o
pneu = M * np.matrix(v).T
print(pneu) # res: 0.0, 2.23, 0.0 : ok

[[0.        ]
 [2.23606798]
 [0.        ]]


In [7]:
ve = np.array([2,2,1]) # in world
Minv = np.linalg.inv(M)
pneu = Minv * np.matrix(ve).T
#pneu = pneu + np.matrix(o).T
print(pneu) # 2.89, 4.6, 1 ok

# and back
pneu = pneu - np.matrix(o).T
pneu = M * np.matrix(pneu)
print(pneu) # res: 2,2,1 : ok

[[0.89442719]
 [2.68328157]
 [1.        ]]
[[-0.68328157]
 [ 1.10557281]
 [ 1.        ]]


In [16]:
import tifffile
tifffile.imsave("test.tiff", rgbimg)

In [129]:
pA = np.matrix([-301.0,-253.0,1079.0])
pB = np.matrix([277.0,-271.0,1064.0])
pC = np.matrix([-295.0,137.0,1072.0]) #[-288.0,137.0,1072.0])
pD = np.matrix([290.0,118.0,1060.0])
print(type(pA))
print(pA.dtype)

<class 'numpy.matrix'>
float64


In [130]:
pAB = pB-pA
lenpAB = np.linalg.norm(pAB)
print('AB:',pAB, '= A:',pA,'- B:',pB )
print('LenAB: {: 0.2f}'.format(lenpAB))

AB: [[578. -18. -15.]] = A: [[-301. -253. 1079.]] - B: [[ 277. -271. 1064.]]
LenAB:  578.47


In [131]:
pCD = pC-pD
lenpCD = np.linalg.norm(pCD)
print('CD:',pCD, '= C:',pC,'- D:',pD )
print('LenCD: {: 0.2f}'.format(lenpCD))

CD: [[-585.   19.   12.]] = C: [[-295.  137. 1072.]] - D: [[ 290.  118. 1060.]]
LenCD:  585.43


In [132]:
pAC = pC - pA
pAB_unit = pAB / np.linalg.norm(pAB)
print('pAB_unit: {}'.format(pAB_unit))
scalarAB = np.dot(pAC,pAB_unit.T)
print('scalarAB: {}'.format(scalarAB))

pAB_unit: [[ 0.999 -0.031 -0.026]]
scalarAB: [[-5.959]]


In [133]:
# distance of AB from A, where orthogonal vector start towards C
posOnAB = scalarAB * pAB_unit
print(posOnAB)

[[-5.954  0.185  0.155]]


In [ ]:
# test optimization for box corner points which do not lie in same plane...
#