In [1]:
import numpy as np
import math

In [2]:
thetaX = math.radians(30.0)
thetaY = math.radians(20.0)
thetaZ = math.radians(10.0)

Rx = np.matrix([[1,0,0],[0,math.cos(thetaX),-math.sin(thetaX)],[0,math.sin(thetaX),math.cos(thetaX)]])
print('Rx:',Rx)
Ry = np.matrix([[math.cos(thetaY),0,math.sin(thetaY)],[0,1,0],[-math.sin(thetaY),0,math.cos(thetaY)]])
print('Ry:',Ry)
Rz = np.matrix([[math.cos(thetaZ),-math.sin(thetaZ),0],[math.sin(thetaZ),math.cos(thetaZ),0],[0,0,1]])
print('Rz:',Rz)

Rx: [[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]
Ry: [[ 0.93969262  0.          0.34202014]
 [ 0.          1.          0.        ]
 [-0.34202014  0.          0.93969262]]
Rz: [[ 0.98480775 -0.17364818  0.        ]
 [ 0.17364818  0.98480775  0.        ]
 [ 0.          0.          1.        ]]


In [3]:
k = Rx*Rz
print(k)
p = np.matrix([[0],[1],[0]])
print(p.shape)
pneu = k*p
print(pneu)

[[ 0.98480775 -0.17364818  0.        ]
 [ 0.15038373  0.85286853 -0.5       ]
 [ 0.08682409  0.49240388  0.8660254 ]]
(3, 1)
[[-0.17364818]
 [ 0.85286853]
 [ 0.49240388]]


In [4]:
k = Rx
p = np.matrix([[0],[1],[0]])
pneu = k*p
print(pneu)

k = Rz*Rx
p = np.matrix([[0],[1],[0]])
pneu = k*p
print(pneu)


[[0.       ]
 [0.8660254]
 [0.5      ]]
[[-0.15038373]
 [ 0.85286853]
 [ 0.5       ]]
