In [10]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,2,2],[2,2,2],[2,2,2]])

In [15]:
a2 = a*a
print('test:',a2)
b2 = b*b
print(b2)
apb = a2+b2
print(apb)
print(np.sqrt(apb))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[ 5  8 13]
 [20 29 40]
 [53 68 85]]
[[2.23606798 2.82842712 3.60555128]
 [4.47213595 5.38516481 6.32455532]
 [7.28010989 8.24621125 9.21954446]]


In [12]:
a*b # add element wise

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

In [ ]:
a@b # multi matrices