### Computertomographie

__Hinweis:__ Ich habe hier absichtlich eine andere Notation gewählt als in der Vorlesung. Die Berechnung und das Gleichungssystems sind aber nach wie vor das Gleiche. Ich möchte Ihnen damit nur zeigen, dass nur die leichte Änderung der Notation das Problem nicht schwieriger wird. 

Bei der Computertomographie soll die Dichteverteilung innerhalb eines Objektes bestimmen werden, ohne das Objekt zu zerschneiden. Das Objekt wird dazu mit einer Vielzahl von Strahlen ${S_k} {k \in K}$ durchleuchtet

![Idee der Computertomographie](./images/tomo1.png)

und für jeden Strahl $S_k$ wird der Intensitätsverlust bestimmt, welcher beim Durchdringen des Objektes auftritt. Aus den Intensitätsverlusten lässt sich dann die Dichteverteilung im Objekt rekonstruieren.

Grundlage der Rekonstruktion ist die folgende Gleichung, welche Dichte $\rho(x)$ und Intensitätsverlust $I_0(k)/I_1(k)$ in Zusammenhang setzt:

$$
log\left( \frac{I_0^{(k)}}{I_1^{(k)}} \right) = \int_{S_k} \rho(s) ds	
$$

Die rechte Seite der Gleichung bestimmt den Intensitätsverlust entlang des Strahles $S_k$ durch das Integral über die Dichte, welche proportional zur Absorption ist. Die linke Seite ist der logarithmierte Intensitätsverlust zwischen Anfang und Ende eines Strahls. Die Intensitäten $I_0^{(k)}$ und $I_1^{(k)}$ sind experimentell bestimmbare Größen, was die Voraussetzung für die Rekonstruktion der Dichte $\rho(x)$ im Objekt ist. Die obige Gleichung bekommt eine besonders einfache Form, wenn die Dichte innerhalb des Objektes stückweise konstant ist (wie z.B. in Abbildung 2(a)). Ein Strahl $S_k$ lässt sich dann in mehrere Segmente $\lambda_1 . . . \lambda_n$ mit Länge $|\lambda_i|$ unterteilen, über welchen die Dichte $\rho(x)$ einen konstanten Wert $\rho_i$ hat. Für Gleichung 1 gilt dann

![Idee der Computertomographie](./images/tomo2.png)

$$
log\left( \frac{I_0^{(k)}}{I_1^{(k)}} \right) = \int_{S_k} \rho(s) ds = \sum_{i=1}^n \int_{\lambda_i} \rho(s) ds = \sum_{i=1}^n |\lambda_i| \rho_i
$$

Diese Vereinfachung wird bei der Computertomographie ausgenutzt. Um die Dichteverteilung innerhalb des Objektes näherungsweise zu bestimmen, wird ein Raster über das Objekt gelegt und für jeden Quadranten des Rasters angenommen, dass die Dichte darin konstant ist. Dabei bezeichnet $Q_{ij}$ den Quadranten in der $i$-ten Zeile und $j$-ten Spalte eines $n \times n$-Raster, $\rho_{ij}$ die Dichte im Quadranten $Q_{ij}$ und $L_{ij}^{(k)}$ die Länge des Schnittes des Strahls $S_k$ mit dem Quadranten $Q_{ij}$. Aus der voherigen Gleichung erhalten wir dann:

$$
V_k = log\left( \frac{I_0}{I_1} \right) = \sum_{i,j=1}^n \int_{Q_{ij} \cap S_k} \rho_{ij} ds = \sum_{i,j=1}^n L_{ij}^{(k)} \rho_{ij}
$$

In der Vorlesung hatten wir das in dieser Form hergeleitet für die Längen $\lambda_{ij}$:  

$$
I_1 = I_0 \cdot \prod_{ij} e^{- \rho_{ij} \, {|{\lambda_{ij}}|}}
$$

Wenn wir durch $I_0$ dividieren und logarithmieren erhalten wir

$$
log\left( \frac{I_0}{I_1} \right) = - \sum_{ij} |{\lambda_{ij}}| \rho_{ij}
$$

Um das Minuszeichen wegzubekommen nutzen wir eine Umstellung $-\log( y / x) = \log( x / y)$, unsere Abschwächungskoeffizienten werden zu unseren Unbekannten $x_{ij}$ und wir erhalten

$$log\left( \frac{I_0}{I_1} \right) = \sum_{ij} x_{ij} \, \lambda_{ij}$$ 

Das sieht für einige vielleicht erstmal schlimm aus, wird aber aus dem Stoff der Vorlesung und dem vorgegebenen SourceCode hoffentlich klarer. Die Gleichung 3 ist ein lineares Gleichungssystem mit einer Gleichung für jeden Strahl und den Dichten der Quadranten als Unbekannten. In Matrixnotation $Ax = b$ lässt sich dieses Gleichungssystem folgendermaßen aufschreiben:

$$
\underbrace{\begin{pmatrix}
	L_{11}^{(1)} & L_{12}^{(1)} & \cdots & 	L_{1n}^{(1)} & L_{21}^{(1)} & L_{22}^{(1)} & \cdots & L_{nn}^{(1)} \\
	L_{11}^{(2)} & L_{12}^{(2)} & \cdots & 	L_{1n}^{(2)} & L_{21}^{(2)} & L_{22}^{(2)} & \cdots & L_{nn}^{(2)} \\
	\vdots & \vdots & \cdots & 	\vdots & \vdots & \vdots) & \cdots & \vdots \\		
	L_{11}^{(K)} & L_{12}^{(K)} & \cdots & 	L_{1n}^{(K)} & L_{21}^{(K)} & L_{22}^{(K)} & \cdots & L_{nn}^{(K)} 			 
\end{pmatrix}}_\text{A} \cdot \underbrace{\begin{pmatrix}
	x_{11} \\ x_{12} \\ \vdots \\ x_{1n} \\ x_{21} \\ x_{22} \\ \vdots \\ x_{nn} 
\end{pmatrix}}_\text{x} = \underbrace{\begin{pmatrix}
	V_1 \\ V_2 \\ \\ \vdots \\ \\ V_K
\end{pmatrix}}_\text{b}
$$

mit $A \in \mathbb{R}^{K \times n^2}$, $x \in \mathbb{R}^{n^2}$ und $b \in \mathbb{R}^{K}$. In der Regel sind sinnvolle Ergebnisse nur zu erwarten, wenn die Anzahl der Gleichungen $K$ (d.h. die Anzahl der Strahlen) größer ist als die Anzahl $n^2$ der Quadranten des Rasters. Es handelt sich dann um ein überbestimmtes Gleichungssystem, welches mittels Methoden der Ausgleichsrechnung gelöst werden muss. 

Bei der Computertomographie werden nicht beliebige Strahlen verwendet, sondern eine Reihe von Aufnahmen mit parallelen Strahlen aus verschiedenen Winkeln gemacht (Abbildung 1). Eine Matrix, die in jeder Spalte die für eine Aufnahme ermittelten Intensitäten $I_1^{(k)}$ enthält, heißt Sinogramm (Abbildung 3 oben). Nach dem Lösen des Gleichungssystems im Least-Squares Sinne erhalten sie die rekonstruierten Ergebnisse, wie in Abbildung 3 unten zu sehen. 

![Sinograph und Ergebnisse](./images/result.png)


#### Einfaches Beispiel:

Schauen wir uns das ganze am einfachen Beispiel aus der Vorlesung an (Schauen Sie hierzu in die Tafelnotizen der Veranstaltung).

In [6]:
import scipy.linalg
import numpy as np
#L = np.matrix('1 1 0 0; 0 0 1 1; 1 0 1 0; 0 1 0 1')
L = np.matrix('1 1 0 0; 0 0 1 1; 1 0 1 0; 0 0 0 1')
#b = np.matrix('-1; -5; -2; -4')
b = np.matrix('-1; -5; -2; -3')

print(L, b)
#x = scipy.linalg.solve(L,b)
#x = solve(L,b)
x = np.linalg.solve(L,b)
# 2**x
print('Solution:',x)

[[1 1 0 0]
 [0 0 1 1]
 [1 0 1 0]
 [0 0 0 1]] [[-1]
 [-5]
 [-2]
 [-3]]
Solution: [[ 0.]
 [-1.]
 [-2.]
 [-3.]]
