#### Knapsack Problem 

Dieses Problem kann man mit Dynamischer Programmierung gut lösen, da es sich gut in Teilprobleme aufteilen lässt. Siehe Erklärung in den Folien.

In [2]:
import sys
import numpy as np

def knapsack1d(items, maxweight):
    """
    1D Knapsack (an item with a specific weight and only a single value). 
    A lookup table is created of maxweight+1 rows for the capacity and len(items+1) cols 
    for the number of possible items. 
    """
    
    
    lookup = np.zeros((maxweight+1, len(items)+1))

    # Enumerate through the items and fill in the lookup table
    # i => columns - number of items
    for i, (value, weight) in enumerate(items):
        
        # the first column is filled with zeros so we can skip it
        i += 1
        # iterate over rows
        for capacity in range(maxweight + 1):
            
            # Handle the case where the weight of the current item is greater
            # than the "running capacity" - we can't add it to the knapsack
            if weight > capacity:
                lookup[capacity, i] = lookup[capacity, i - 1]
            else:
                # Otherwise, we must choose between two possible candidate values:
                # 1) the value of "running capacity" as it stands with the last item
                #    that was computed; if this is larger, then we skip the current item
                # 2) the value of the current item plus the value of a previously computed
                #    set of items, constrained by the amount of capacity that would be left
                #    in the knapsack (running capacity - item's weight)
                candidateA = lookup[capacity, i - 1]
                candidateB = lookup[capacity - weight, i - 1] + value
                
                # Just take the maximum of the two candidates; by doing this, we are
                # in effect "setting in stone" the best value so far for a particular
                # prefix of the items, and for a particular "prefix" of knapsack capacities
                lookup[capacity, i] = max(candidateA, candidateB)

    # Reconstruction
    # Iterate through the values table, and check
    # to see which of the two candidates were chosen. See slides
    selection = []
    i = len(items)
    j = maxweight
    while i > 0:
        # start last row and last column
        # if values are not the same - take the item
        if lookup[j, i] != lookup[j, i - 1]:
            selection.append(items[i - 1])
            j -= items[i - 1][1]
        i -= 1

    # Reverse the selection list, so that it is presented
    # in the order that it was given
    selection.reverse()
    
    print(lookup)
    # Return the best value, and the reconstruction list
    return lookup[maxweight, len(items)], selection


maxweight = 7
items = [(16,2),(19,3),(23,4),(28,5)]
value, selected_items = knapsack1d(items, maxweight)
print("bag is worth:", value)
print("selected items:", selected_items)
# TODO sum over all

0
1
2
3
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [16. 16. 16. 16.  0.]
 [16. 19. 19. 19.  0.]
 [16. 19. 23. 23.  0.]
 [16. 35. 35. 35.  0.]
 [16. 35. 39. 39.  0.]
 [16. 35. 42. 44.  0.]]
bag is worth: 0.0
selected items: [(28, 5)]
