<h1 style="font-size:2.5em;text-align:center">Visual and Scientific Computing</h1>
<h2 style="text-align:center">Basics</h2>
<h3 style="text-align:center">WiSe 2019/20</h3>
<p style="text-align:justify">Das Lernziel dieser Übungsaufgabe ist mit der Programmiersprache Python und der Bibliothek Numpy vertraut zu werden, um diese dann als Werkzeug in den weiteren Übungen einzusetzen. Machen Sie sich deshalb bitte so gut es geht damit vertraut und nutzen Sie dafür auch bitte Online-Resourcen wie <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/">https://docs.scipy.org/doc/numpy-1.13.0/reference/</a> und <a href="https://docs.python.org/3/">https://docs.python.org/3/</a>.</p>

## Aufgabe 1: Python Einführung (5 Punkte)

<ol style="list-style: lower-alpha"><li>Um sich mit der Programmiersprache Python vertraut zu machen, implementieren Sie einen einfachen Bubblesort-Algorithmus. Eine beispielhafte Eingabe und Ausgabe könnte so aussehen:</li></ol>
<pre>Eingabe: [ 5 14 10  7  2 13  1 12  6  9  0  3  8 11  4]
Ausgabe: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]</pre>

In [20]:
def bubblesort(liste:list) -> (list):
    """
    Implements Bubblesort using an list as input and
    returning a sorted list

    :param list
    :return: list
    """
    # liste.sort()
    # print('Easy peasy way:', liste)
    
    # test arange
    #print(len(liste))
    #x = np.arange(len(liste),-1,-1)
    #print(x)
    
    # TODO: Implement Bubblesort
    for backIdx in range(len(liste),-1,-1):
        for frontIdx in range(1,backIdx):
            #print('frontIdx:',frontIdx, 'backIdx:',backIdx)
            #print('frontIdx-1:',frontIdx-1, 'elem:',liste[frontIdx-1], 'frontIdx:',frontIdx, 'elem:',liste[frontIdx])
            if (liste[frontIdx-1] > liste[frontIdx]):
                tmp = liste[frontIdx-1]
                liste[frontIdx-1] = liste[frontIdx]
                liste[frontIdx] = tmp
                #print('is bigger') 
                
    return liste

In [21]:
sorted_list = bubblesort([52, 18, 65, 61, 31, 86, 36, 15, 22, 13])

print('Self made bubble sort:',sorted_list)

Self made bubble sort: [13, 15, 18, 22, 31, 36, 52, 61, 65, 86]


## Aufgabe 2: Numpy Einführung (5 Punkte)

<p style="margin-left:2em">Die Bibliothek <em>Numpy</em> ist sehr umfangreich und wir werden auch nicht jede Funktionalität brauchen, aber es ist wichtig mit den grundlegenden Datenstrukturen vertraut zu sein. Ich habe hier eine Liste von kleinen Aufgaben zusammengestellt, die Sie in der Datei <em>numpy_basic.py</em> beantworten sollen. <strong>Suchen Sie sich insgesamt 14 (von 23) Sterne zusammen und implementieren Sie diese</strong>. Das ist häufig ein Einzeiler oder Zweizeiler. Die Musterlösung benötigt in jeder Teilaufgabe maximal drei Zeilen. Es muss aber nicht krampfhaft versucht werden diese Vorgabe zu erreichen, dies soll nur ein Hinweis darauf sein, dass Sie keinen langen Code schreiben müssen. Lesen Sie sich selbstständig in die Dokumentation ein und versuchen Sie die Fragen mit den notwendigen Numpy-Funktionen zu beantworten. Sollten Sie keine Funktion finden, implementieren Sie eine Lösung selbst in einer kleinen Funktion. Sie können auch im Kursforum nach Hilfe suchen. <strong>Bitten geben Sie die Lösung jeweils auf der Konsole aus (mittels print)</strong>. Hinweis: die print Anweisung zählt nicht zu dem Einzeiler oder Zweizeiler, wenn im Hinweis also steht <i>geht in einer Zeile</i> muss in dieser nicht auch noch die print Anweisung kommen.</p>

In [22]:
import numpy as np

<p style="margin-left:2em">a) (*) Erzeugen Sie einen Vektor a mit Nullen der Länge 10 (10 Elemente) und setzen den Wert des 5. Elementes auf eine 1.</p>

In [23]:
# Erzeugen Sie einen Vektor mit Nullen der Länge 10 und setzen den Wert des 5. Elementes auf eine 1.
vec_a = np.zeros(10)
vec_a[5] = 1
print('Print vec_a:',vec_a)
print('Has only one dim:',vec_a.shape)

Print vec_a: [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
Has only one dim: (10,)


<p style="margin-left:2em">b) (*) Erzeugen Sie einen Vektor b mit Ganzahl-Werten von 10 bis 49 (geht in einer Zeile).</p>

In [24]:
# Erzeugen Sie einen Vektor mit Ganzzahl-Werten von 10 bis 49 (geht in einer Zeile).

vec_b = np.arange(10,49+1)
print('Arange vec_b:',vec_b)
vec_b.dtype

# das hier wird float64
#vec_b = np.linspace(10,49,40)
#print('Linspace vec_b:',vec_b)
#vec_b.dtype

Arange vec_b: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


dtype('int64')

<p style="margin-left:2em">c) (*) Erzeugen Sie einen Vektor mit 8 Einträgen zwischen -1 und 1 bei dem alle Werte die gleichen Abstände habe und sowohl -1 als auch 1 enthalten sind (geht in einer Zeile).</p>

In [25]:
# Erzeugen Sie einen Vektor mit 8 Einträgen zwischen -1 und 1 bei dem alle Werte die gleichen Abstände habe und sowohl -1 als auch 1 enthalten sind (geht in einer Zeile). Hinweis: guckt euch den Unterschied zwischen numpy.arange und numpy.linspace welche Funktion passt besser?.
vec_c = np.linspace(-1., 1., 8)
print('vec_c:',vec_c)

vec_c: [-1.         -0.71428571 -0.42857143 -0.14285714  0.14285714  0.42857143
  0.71428571  1.        ]


<p style="margin-left:2em">d) (*) Geben Sie nur das Stück (slice) von Vektor b) aus, das die Zahlen 21 bis 38 (Stellen 11 bis 28) beinhaltet (geht in einer Zeile).</p>

In [26]:
# Geben Sie nur das Stück (slice) von Vektor b) aus, das die Zahlen 21 bis 38 (Stellen 11 bis 28) beinhaltet (geht in einer Zeile).
vec_d = vec_b[11:28+1]
print(vec_d)

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]


<p style="margin-left:2em">e) (*) Ändern Sie den Vektor b) indem sie das Stück (slice) von Stelle 15 bis <strong>einschließlich</strong> Stelle 25 mit den Werten negierten Werten von Stelle 1 bis <strong>einschließlich</strong> Stelle 11 überschreiben (geht in einer Zeile).</p>

In [27]:
# Ändern Sie den Vektor b) indem sie das Stück (slice) von Stelle 15 bis einschließlich Stelle 25 mit den Werten negierten Werten von Stelle 1 bis einschließlich Stelle 11 überschreiben (geht in einer Zeile).
vec_b[15:25+1] = - vec_b[1:11+1]
print(vec_b)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24 -11 -12 -13
 -14 -15 -16 -17 -18 -19 -20 -21  36  37  38  39  40  41  42  43  44  45
  46  47  48  49]


<p style="margin-left:2em">f) (*) Drehen Sie die Werte des Vektors aus b) oder a) um (geht in einer Zeile).</p>

In [28]:
# Drehen Sie die Werte des Vektors aus a) oder b) um (geht in einer Zeile).
vec_f = np.flip(vec_b, axis=0)
print('vec_b inverse:',vec_f)
#vec_f = np.flip(vec_a, axis=0)
#print('vec_a inverse:',vec_f)
vec_f.shape

vec_b inverse: [ 49  48  47  46  45  44  43  42  41  40  39  38  37  36 -21 -20 -19 -18
 -17 -16 -15 -14 -13 -12 -11  24  23  22  21  20  19  18  17  16  15  14
  13  12  11  10]


(40,)

<p style="margin-left:2em">g) (*) Summieren Sie alle Werte in einem Array (geht in einer Zeile).</p>

In [29]:
# Summieren Sie alle Werte in einem Array.
val_g = np.sum(vec_b)
print('Sum vec_b:',val_g)

Sum vec_b: 674


<p style="margin-left:2em">h) (*) Erzeugen Sie eine 4x4 Matrix mit den Werte 0 (links oben) bis 15 (rechts unten) (geht in einer Zeile).</p>

In [30]:
# Erzeugen Sie eine 4x4 Matrix mit den Werte 0 (links oben) bis 15 (rechts unten) (geht in einer Zeile). Tip: Schauen Sie sich numpy.reshape an
mat_h = np.arange(0,16).reshape(4,4)
print('Reshaped vector:\n',mat_h)
print('Shape dim:',mat_h.shape)

Reshaped vector:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Shape dim: (4, 4)


<p style="margin-left:2em">i) (*) Erzeugen Sie eine 5x3 Matrix mit Zufallswerteintegers zwischen 0-100 (geht in einer Zeile).</p>

In [31]:
# Erzeugen Sie eine 5x3 Matrix mit Zufallswerteintegers zwischen 0-100 (geht in einer Zeile).
mat_i = np.random.randint(low=0, high=100+1, size=3*5).reshape(5,3)
print('mat_i shape:',mat_i.shape)
print(mat_i)

mat_i shape: (5, 3)
[[53 23 63]
 [87 20 62]
 [77  6 32]
 [13 51 75]
 [16 45 19]]


<p style="margin-left:2em">j) (*) Multiplizieren Sie eine 4x3 Matrix mit einer 3x2 Matrix (geht zwar in einer Zeile, aber benutzen Sie lieber Hilfsvariablen und drei Zeilen).</p>

In [32]:
# Multiplizieren Sie eine 4x3 Matrix mit einer 3x2 Matrix (geht zwar in einer Zeile, aber benutzen Sie lieber Hilfsvariablen und drei Zeilen).
mat_0 = np.random.randint(low=0, high=100+1, size=4*3).reshape(4,3)
# print(mat_0.shape)
mat_1 = np.random.randint(low=0, high=100+1, size=3*2).reshape(3,2)
# print(mat_1.shape)
# not working: # mat_j = mat_0 * mat_1
# print(type(mat_0)) # <class 'numpy.ndarray'>

mat_j = np.mat(mat_0) * np.mat(mat_1)
# print(mat_j.shape) 
# print(type(mat_j)) # <class 'numpy.matrix'>
print('ndarray casted to matrix works with *:\n',mat_j)
# oder
mat_j = mat_0 @ mat_1
print('Or via @:\n',mat_j)

# ndarray dot proct test
#A = np.random.random((4,5))
#B = np.random.random((5,3))
#C = A.dot(B)
#print (C)
#type(A)

ndarray casted to matrix works with *:
 [[ 7718  1632]
 [ 7688  2300]
 [ 5557   966]
 [11967  5235]]
Or via @:
 [[ 7718  1632]
 [ 7688  2300]
 [ 5557   966]
 [11967  5235]]


<p style="margin-left:2em">k) (*) Erzeugen Sie eine 5x5 Matrix und geben Sie jeweils die geraden und die ungeraden Zeile aus (geht jeweils in einer Zeile).</p>

In [33]:
# Erzeugen Sie eine 5x5 Matrix und geben Sie jeweils die geraden und die ungeraden Zeile aus (geht jeweils in einer Zeile).
mat_k = np.mat(np.random.randint(low=0, high=100+1, size=5*5).reshape(5,5))
print('mat_k full:\n',mat_k)
print('Gerade Zeilen 0,2,4:\n',mat_k[::2])
print('Ungerade Zeilen 1,3:\n',mat_k[1::2])


mat_k full:
 [[72 30 30 56 61]
 [49 40 94 64 75]
 [54  5 45 39 42]
 [16 43 91 29 77]
 [91 65 54 62 15]]
Gerade Zeilen 0,2,4:
 [[72 30 30 56 61]
 [54  5 45 39 42]
 [91 65 54 62 15]]
Ungerade Zeilen 1,3:
 [[49 40 94 64 75]
 [16 43 91 29 77]]


<p style="margin-left:2em">l) (**) Erzeuge eine 5x5 Matrix mit Zufallswerteintegers zwischen 0-100 und finde deren Maximum und Minimum und normalisieren Sie die Werte (sodass alle Werte zwischen 0 und 1 liegen - ein Wert wird 1 (max) sein und einer 0 (min)).</p>

In [34]:
# Erzeuge eine 5x5 Matrix mit Zufallsintegers zwischen 0-100 und finde deren Maximum und Minimum und normalisieren Sie die Werte (sodass alle Werte zwischen 0 und 1 liegen - ein Wert wird 1 (max) sein und einer 0 (min)).
# Hinweis: D.h. Sie muessen die Werte normalisieren (R - R_min) / (R_max - R_min)
mat_l = np.mat(np.random.randint(low=0, high=100+1, size=5*5).reshape(5,5))
# print(mat_l)
max = mat_l.max()
min = mat_l.min()
diff = max - min
# print(diff)
mat_l = (mat_l - min)/diff
print('Normalized matrix:\n',mat_l)

Normalized matrix:
 [[ 1.          0.44444444  0.24242424  0.46464646  0.64646465]
 [ 0.21212121  0.28282828  0.43434343  0.57575758  1.        ]
 [ 0.          0.13131313  0.90909091  0.25252525  0.5959596 ]
 [ 0.92929293  0.61616162  0.76767677  0.33333333  1.        ]
 [ 0.03030303  0.83838384  0.60606061  0.18181818  0.28282828]]


<p style="margin-left:2em">m) (**) Extrahieren Sie den Integer-Anteil eine Arrays von zufälliger Zahlen zwischen 0-10 auf 3 verschiedene Arten.</p>

In [35]:
# Extrahieren Sie den Integer-Anteil eine Arrays von zufälliger Zahlen zwischen 0-10 auf 3 verschiedene Arten.
vec_m = 10*np.random.sample(10)
#print(vec_m)
print('Frist <floor>:',np.floor(vec_m))
import math
vec_float, vec_int = np.modf(vec_m);
print('Second <math.modf>:', vec_int) 
print('Third <astype>:',vec_m.astype(int))

Frist <floor>: [ 6.  9.  2.  6.  4.  6.  5.  6.  5.  2.]
Second <math.modf>: [ 6.  9.  2.  6.  4.  6.  5.  6.  5.  2.]
Third <astype>: [6 9 2 6 4 6 5 6 5 2]


<p style="margin-left:2em">n) (**) Erzeugen Sie eine Matrix M der Größe 4x3 und einen Vektor v mit Länge 3. Multiplizieren Sie jeden Spalteneintrag aus mit der kompletten Spalte aus M. Nutzen Sie dafür Broadcasting.</p>

In [36]:
# Erzeugen Sie eine Matrix $M$ der Größe 4x3 und einen Vektor $v$ mit Länge 3. Multiplizieren Sie jeden Spalteneintrag aus $v$ mit der kompletten Spalte aus $M$. Nutzen Sie dafür Broadcasting.
vec_n = np.random.randint(low=0, high=10+1, size=4*3).reshape(4,3)
vec_3 = np.array([-1,0,-1])
# print(vec_3.shape)
vec_mult = vec_n * vec_3
print(vec_mult)

[[-9  0 -6]
 [-6  0 -4]
 [-4  0 -6]
 [-3  0 -1]]


<p style="margin-left:2em">o) (3*) Erzeugen Sie einen Zufallsmatrix der Größe 10x2, die Sie als Kartesische Koordinateninterpretieren können ([[x0, y0],[x1, y1],[x2, y2]]). Konvertieren Sie diese in Polarkoordinaten <a href="https://de.wikipedia.org/wiki/Polarkoordinaten">https://de.wikipedia.org/wiki/Polarkoordinaten</a>.</p>

In [37]:
# (***) Erzeugen Sie einen Zufallsmatrix der Größe 10x2, die Sie als Kartesische Koordinaten interpretieren können ([[x0, y0],[x1, y1],[x2, y2]]).
# Konvertieren Sie diese in Polarkoordinaten \url{https://de.wikipedia.org/wiki/Polarkoordinaten}.
# Hinweis: nutzen Sie fuer die Berechnung des Winkel np.arctan2 und geben Sie jeweils Radius und Winkel als Vektor aus
vec_o = np.random.randint(low=-10, high=10+1, size=10*2).reshape(10,2)
print('Input x,y values:\n',vec_o)
vec_angle = np.arctan2(vec_o[:,0],vec_o[:,1])
vec_radius = np.linalg.norm(vec_o,axis=1)
# concatenate 2 numpy arrays: column-wise
mat_polar = np.column_stack((vec_angle,vec_radius))
print('Output polar coords in [angle,radius]:\n',mat_polar)

Input x,y values:
 [[  0  -5]
 [  0   4]
 [ -4   1]
 [ -8   1]
 [-10  -3]
 [  3  -5]
 [ -4  -6]
 [ -5   1]
 [-10   2]
 [ -6  -1]]
Output polar coords in [angle,radius]:
 [[  3.14159265   5.        ]
 [  0.           4.        ]
 [ -1.32581766   4.12310563]
 [ -1.44644133   8.06225775]
 [ -1.86225312  10.44030651]
 [  2.60117315   5.83095189]
 [ -2.55359005   7.21110255]
 [ -1.37340077   5.09901951]
 [ -1.37340077  10.19803903]
 [ -1.735945     6.08276253]]


<p style="margin-left:2em">p) (3*) Erzeugen Sie einen Matrix der Größe 6x2, die Sie als Kartesische Koordinaten interpretieren können ([[x0, y0],[x1, y1],[x2, y2]]). Schreiben Sie eine Funktion, die alle Punkt-Punkt Abstände berechnet und in einer 6x6 Matrix ausgibt.</p>

In [38]:
# (***) Erzeugen Sie einen Matrix der Größe 6x2, die Sie als Kartesische Koordinaten interpretieren können ([[x0, y0],[x1, y1],[x2, y2]]).
# Schreiben Sie eine Funktion, die alle Punkt-Punkt Abstände berechnet.

#a = np.random.randint(6, size=(5, 2))

def distP(points):
    mat_out = np.zeros(shape=(6,6))
    #r,c = points.shape
    for n in range(len(points)):
        for m in range(len(points)):
            mat_out[n,m] = np.linalg.norm(points[n]-points[m])
            
    return mat_out

    
vec_p = np.random.randint(low=-10, high=10+1, size=6*2).reshape(6,2)
print('Input point [x,y]:\n',vec_p)
out = distP(vec_p)
print('Output distances:\n',out)

Input point [x,y]:
 [[-4 -5]
 [ 4  3]
 [ 9  8]
 [-5 -6]
 [ 0  3]
 [10  1]]
Output distances:
 [[  0.          11.3137085   18.38477631   1.41421356   8.94427191
   15.23154621]
 [ 11.3137085    0.           7.07106781  12.72792206   4.           6.32455532]
 [ 18.38477631   7.07106781   0.          19.79898987  10.29563014
    7.07106781]
 [  1.41421356  12.72792206  19.79898987   0.          10.29563014
   16.55294536]
 [  8.94427191   4.          10.29563014  10.29563014   0.          10.19803903]
 [ 15.23154621   6.32455532   7.07106781  16.55294536  10.19803903   0.        ]]
