In [2]:
import numpy as np
import scipy as sp
import matplotlib as pl

In [46]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[1,2,3],[1,2,3]])
C = A*B
print('Type:',type(C))
print('Point wise mult:',C)

# aber works @ for array multi
D = A @ B.T
print('Now matrix multi by @:\n',D)

Type: <class 'numpy.ndarray'>
Point wise mult: [[1 4 9]
 [1 4 9]]
Now matrix multi by @:
 [[14 14]
 [14 14]]


In [47]:
A = np.matrix([[1,2,3],[1,2,3]])
B = np.matrix([[1,2,3],[1,2,3]])
C = A * B.T
print('Type:',type(C))
print('Matrix mult:\n',C)

# with matrix element wise multi!!!
D = np.multiply(A,B)
D



Type: <class 'numpy.matrix'>
Matrix mult:
 [[14 14]
 [14 14]]


matrix([[1, 4, 9],
        [1, 4, 9]])

In [48]:
A = np.matrix('1,2,3;1,2,3')
A

matrix([[1, 2, 3],
        [1, 2, 3]])

In [49]:
E = np.arange(20).reshape(4,5)
print(type(E))
print('Mat full:\n',E)
print('Sliced:\n',E[1:3,1:3])

<class 'numpy.ndarray'>
Mat full:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Sliced:
 [[ 6  7]
 [11 12]]


In [50]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

vv = np.tile(v,(4,1))
print(x,'\n',vv)

# broadcast
print(x+v)

# is equal to: # x[:] + v

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
 [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [51]:
# floating points
s = 1.4
v = np.matrix('1,2,3')
print(v.shape)
print(v.T.shape)

M = np.matrix('1,2;2,3')
print(M)

T = np.random.rand(3,3,2)
print(T.shape)
print(T)
print(type(T))

(1, 3)
(3, 1)
[[1 2]
 [2 3]]
(3, 3, 2)
[[[0.55615317 0.8780514 ]
  [0.31590125 0.31560144]
  [0.22680208 0.07592859]]

 [[0.09790453 0.26898608]
  [0.37924531 0.20176908]
  [0.38877537 0.88467916]]

 [[0.38977594 0.44704693]
  [0.69115398 0.56888572]
  [0.8262351  0.3924879 ]]]
<class 'numpy.ndarray'>


In [52]:
v1 = np.matrix('1,2,3')
v2 = np.matrix('1,2,3')
print(v1.dot(v2.T))

[[14]]


In [53]:
v1 = np.matrix('1,2,3')
v2 = np.matrix('1,2,3')
print(v1.dot(v2.T))

V1 = np.matrix('1,2,3;1,2,3')
v2 = np.matrix('1,2,3')
print(V1.dot(v2.T))

V1 = np.matrix('1,2,3;1,2,3')
V2 = np.matrix('1,2,3;1,2,3')
print('All vectors with each other:\n',V1.dot(V2.T))

[[14]]
[[14]
 [14]]
All vectors with each other:
 [[14 14]
 [14 14]]


In [66]:
# Gleichungssystem lösen einfachens Beispiel
# Äpfel und Birnen
# 6 Äpfel und 12 Birnen kosten 30€
# 3 Äpfel und 3 Birnen kosten 9€
A = np.matrix('6 12; 3 3')
b = np.matrix('30; 9')

A_inv = np.linalg.inv(A)
x = A_inv * b
print(x)

p = np.mat('3;4')
print('Type:',type(p))
type(p)

[[1.]
 [2.]]
Type: <class 'numpy.matrix'>


numpy.matrix